// Generates generated/ts/contracts.ts from the JSON Schemas. With --check, fails if the committed file is stale.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "generated/ts/contracts.ts");

// Every document schema plus the task-output definitions, as properties of one root so each type is emitted once.
const DOCUMENTS = ["ddl", "object", "rule", "profile", "check-result", "interpretation", "stamp", "signing-gate", "audit-record", "precedent-card", "narration-script", "idea-result", "critique", "ddl-diff", "thread-state", "copy", "models", "render-thresholds"];
const OUTPUTS = ["route_result", "plain_rewrite", "explanation", "profile_draft_result", "precedent_search_result"];
const root = {
  title: "DrawlogicContracts",
  type: "object",
  additionalProperties: false,
  properties: {
    ...Object.fromEntries(DOCUMENTS.map((d) => [d, { $ref: `${d}.schema.json` }])),
    ...Object.fromEntries(OUTPUTS.map((o) => [o, { $ref: `llm-outputs.schema.json#/$defs/${o}` }])),
  },
};

const banner = "/* Generated by contracts/scripts/gen-ts.mjs from contracts/*.schema.json. Do not edit; change the schema and run `npm run gen:ts`. */";
const ts = await compile(root, "DrawlogicContracts", {
  cwd: ROOT,
  bannerComment: banner,
  additionalProperties: false,
  unreachableDefinitions: false,
  strictIndexSignatures: true,
  format: true,
  style: { printWidth: 140 },
});

if (process.argv.includes("--check")) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (current !== ts) {
    console.error("generated/ts/contracts.ts is stale: run `npm run gen:ts` in contracts/ and commit the result.");
    process.exit(1);
  }
  console.log("generated/ts/contracts.ts is up to date.");
} else {
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, ts);
  console.log(`wrote ${path.relative(ROOT, OUT)} (${ts.split("\n").length} lines)`);
}
