"""Generates pydantic v2 models in generated/py/drawlogic_contracts from contracts/*.schema.json.

usage: python scripts/gen_py.py [--check]
Requires the pinned tools in contracts/requirements.txt. --check fails if the committed models are stale.
"""

from __future__ import annotations

import filecmp
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "generated" / "py" / "drawlogic_contracts"


def generate(dest: Path) -> None:
    with tempfile.TemporaryDirectory() as tmp:
        staged = Path(tmp) / "schemas"
        staged.mkdir()
        for schema in sorted(ROOT.glob("*.schema.json")):
            shutil.copy(schema, staged / schema.name)
        subprocess.run(
            [
                sys.executable, "-m", "datamodel_code_generator",
                "--input", str(staged),
                "--input-file-type", "jsonschema",
                "--output", str(dest),
                "--output-model-type", "pydantic_v2.BaseModel",
                "--target-python-version", "3.12",
                "--use-title-as-name",
                "--use-standard-collections",
                "--use-union-operator",
                "--field-constraints",
                "--disable-timestamp",
                "--formatters", "black", "isort",
                "--custom-file-header", "# Generated by contracts/scripts/gen_py.py from contracts/*.schema.json. Do not edit.",
            ],
            check=True,
        )


def main() -> int:
    if "--check" in sys.argv:
        with tempfile.TemporaryDirectory() as tmp:
            fresh = Path(tmp) / "drawlogic_contracts"
            generate(fresh)
            cmp = filecmp.dircmp(fresh, OUT, ignore=["__pycache__"])
            stale = cmp.left_only or cmp.right_only or cmp.diff_files
            if stale:
                print(f"generated/py is stale ({stale}): run `python scripts/gen_py.py` in contracts/ and commit.", file=sys.stderr)
                return 1
        print("generated/py/drawlogic_contracts is up to date.")
        return 0
    if OUT.exists():
        for f in OUT.glob("*.py"):
            f.unlink()
    generate(OUT)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
