"""Drawlogic profiles: versioned jurisdiction, regional, client, office, manufacturer and Generic data (PRD §6, principle 1).

Each profiles/<id>/ directory holds one profile document. Derived fields (rule condition text, coverage) are generated by
profiles/tools.py from the authored data; never edit them by hand.
"""
